### ISSUE TITLE
Incorrect JSON file processing for movie titles with parentheses

### ISSUE THREAD

**Issue by cloudhub** [oklookat/kp2imdb#1]
I've identified an issue where the file processing fails to handle movie titles correctly if they contain parentheses.

`[{"id":"64042","name":"Нарушая запреты","alt_name":"Tra(sgre)dire (2000) 91 мин.","date_added":"26.01.2013, 19:32"}]`

**Expected Behavior:**
The file processing should handle movie titles with parentheses accurately.

**Actual Behavior:**

> .\kp2imdb.exe -m test.json
> wrong title format: Tra(sgre)dire (2000) 91 мин.
> panic: wrong title format: Tra(sgre)dire (2000) 91 мин.
> 
> goroutine 1 [running]:
> main.chk(...)
>         c:/kp2imdb-main/main.go:118
> main.main()
>         c:/kp2imdb-main/main.go:44 +0xdd3

**Movies:**

- https://www.kinopoisk.ru/film/64042
- https://www.kinopoisk.ru/film/722827

**Comment by oklookat** [comment]
Thank you. Fixed it in the new release: https://github.com/oklookat/kp2imdb/releases/tag/v1.0.1
